### PR TITLE
robin, please keep up with pull requests!

### PR DESCRIPTION
**Pull request by elanhickler**
this adds some missing midi messages (still needs improvement) and stricter mouse handling for combo box and slider.

### CODE REVIEW

**Comment by elanhickler** [comment]
> not really convinced, that aftertouch and channelpressure should be dispatched to their own callbacks

Why not? It's a callback. Something changes. Notify. Do something. What other paradigm would you? Why is it different than modwheel or any CC or pitchwheel?

Anyway, it doesn't matter, I think I need to stop trying to make your framework all-inclusive.

**Comment by RobinSchmidt** [comment]
because i consider these types of events more exotic and less important. i mean, there are still many more types of midi events and if you want to have a callback for each of them, it bloats the interface considerably. it's a jugdement call, though

**Comment by RobinSchmidt** [comment]
> What other paradigm would you?

i would say, if some synth wants to respond to such events, it should just override handleMidiMessage

**Comment by elanhickler** [comment]
what is the advantage of not just defining it in the first place?

Bloat the interface? I'd rather have a bloated interface than have to override everything. Overriding causes more bloat.

No one uses more exotic midi messages. But after touch and channel pressure are modern niceties! Also, I would include the midi channel number.

But again, maybe I should actually just be overriding all your stuff and eventually just write my own framework from scratch. We don't have enough of a common goal it seems.

**Comment by elanhickler** [comment]
Sorry I didn't mean to sound confrontational, I just want to understand our needs so we can work together more efficiently.

I still really need your framework, the parametermapper stuff to create my all important product. Please help me get that finished by Christmas, PLEEEZ. After that, then I will not be asking for you to do much more for me, I'll be doing a lot myself after that, and you can focus on DSP and hopefully I will find you some customers.

**Comment by RobinSchmidt** [comment]
> Bloat the interface? I'd rather have a bloated interface than have to override everything. 

i don't understand that. by creating a baseclass-dispatcher for even more midi-events to more individual callbacks, subclasses have to override more individual functions. actually, for a minimal interface, just the handleMidiMessage method would suffice and the subclasses would have to override only this single oen method - which they still can, if they so choose. i just do a dispatch into individual event callbacks (noteOn, controlChange, etc.) for convenience for the more common events

**Comment by elanhickler** [comment]
ok, that's all fine. You want a few for convenience and then if needed more, one should override the midi callback.

**Pull request merged**
