### PR TITLE
Warning fix pass #1 (127 remaining)

### PR DESCRIPTION
**Pull request by lmdsp**
Hi Robin,

can you please incorporate these fixes. 
Some are just annoying warnings that pollute the build output and potentially obscure other serious problems, and a few fix bugs (delete instead of delete[], etc.)

Thanks,
Lorcan

### CODE REVIEW

**Comment by elanhickler** [comment]
Robin, could you deal with this? Lorcan won't be happy if you don't!

**Comment by RobinSchmidt** [comment]
ok - thanks. i didn't notice this immediately but have merged it now

**Comment by elanhickler** [comment]
great. was worried you'd never do it. BTW I paid lorcan time for doing this... he didn't have much else to do at the time.

**Comment by lmdsp** [comment]
@elanhickler It was max 10 min of my time ;) The good thing with modern compilers is that sometimes they do most of the work for you ..

@RobinSchmidt I also run a VS / Xcode static analyzer path every few months, they're really precious tools to find typos and obscure bugs lurking in my codebase. This one https://www.viva64.com/en/b/0457/ is even more advanced, it's free for individual projects as long as you put 2 lines of comments in your source.

**Comment by RobinSchmidt** [comment]
i have never used a static code analyzer before. i just let the vs one run over my rapt/rosic libraries. it complains about some virtual destructors that have been added by you "destructor tag mismatch". actually i don't intend to have runtime polymorphism for my core dsp library objects, so i actually don't really want virtual destructors there. what are good for? made their absence any problems?

i usually build on vs, occasoinally on codeblocks and very rarely on xcode. i guess, most of these warning occured only in xcode? i didn't have them in vs or codeblocks

**Comment by lmdsp** [comment]
Robin, can you point me to some lines of code regarding 'destructor tag mismatch'?
Of course I completely agree on the fact that low-level dsp classes shouldn't have virtual functions.
Static dispatch is king when performance matters.

However I don't recall adding any virtual specifiers where they didn't belong. What the spec requires, and what XCode was complaining about, is that a dtor() must be marked virtual if a class or any its descendants has a virtual member function. Also, the 'override' keyword is really useful to spot errors when you think you're overriding something and are in fact not, because the signature is different.

The warnings occur in VS2017 too if you enable W3 or so if I recall well.

**Comment by RobinSchmidt** [comment]
don't worry, i fixed it. one was in Mapper2D which i have renamed to rsMapper2D - that's why it complained because the destructor was called ~Mapper2D with the rs prefix (there, i really need runtime polymorphism, so i fixed the destructor there). the other one was in in rsLadder. it had one virtual function. i removed the virtual specifier there and removed the virtual destructor

**Comment by RobinSchmidt** [comment]
> he 'override' keyword is really useful to spot errors when you think you're overriding something and are in fact not, because the signature is different.

indeed. i want to add that to overriden functions generally. i also noticed that you removed the virtual specifier from overriden functions. that's fine. i used as as a reminder that it's an override before c++11, but now with the actual override keyword, that would be redundant

**Comment by lmdsp** [comment]
Cool, thanks.
Another one that sometimes comes in is 'final', which as the name implies, prevents any derived classes from overriding. I also noticed the '= default;' reduced code size a bit in my builds.

**Comment by RobinSchmidt** [comment]
>  I also noticed the '= default;' reduced code size a bit in my builds.

as compared to just define an empty one via `{}`? that's interesting. and kinda strange, because the default destructor should be exactly that empty one, shouldn't it?

**Comment by RobinSchmidt** [comment]
btw.  do you remember why you removed the `inline` from `getSample` in `Ladder` (now `rsLadder`)? i'd actually generally like to inline such per sample processing functions. did it make any problems?

**Comment by elanhickler** [comment]
I had the same question. should I put `constructor() = default` `~destructor() = default` for every class I create?

**Comment by lmdsp** [comment]
@RobinSchmidt I must have removed it out of habit. 'inline' is redundant on a member function declaration, it's only taken into account if you put it in a separate definition. And if you do 'float get_sample();' directly in the class declaration it's automatically inline.
I used to put 'forceinline' macros before but in the long run with modern compilers I came the conclusion that's it's best to let the compiler do its optimization job. Better IPO / LTO, less code bloat.

@elanhickler = default is preferred yes IMO, except of course if you have to do non-trivial member initialization

**Comment by RobinSchmidt** [comment]
in this case, the function definition was outside the class. ...aand there's still an inline in front of the actual definition. hmm - what does the compiler do when the declaration has not but the definition has an inline? dunno. and yes, i used to use a forceinline macro too

**Comment by RobinSchmidt** [comment]
ah - ok - i see. it's then redundant in the declaration?

**Comment by elanhickler** [comment]
hey Lorcan, while you're around, please check out this audio demo that sounds like what I was hoping your Superchord could sound like with lots of feedback or whatever the parameter would be called:

https://soundcloud.com/thierry-rochebois-1/axoloti-feedback

I'm pretty sure you just have to allow for higher parameter ranges on one or two of your knobs.

**Pull request merged**
