### PR TITLE
I can't use jura_StringTools unless the functions are defined. With t…

### PR DESCRIPTION
**Pull request by elanhickler**
I can't use jura_StringTools unless the functions are defined. With this change, they are defined.

### CODE REVIEW

**Comment by elanhickler** [comment]
Another way to combine best of both words for any number to midi string and keeping CPU cost down is:

1. create a midi object with some values that pre-defines an array of 128 indexes
2. if the number is above or below 0-127, then calculate string on the fly.

**Comment by RobinSchmidt** [comment]
as for the convention of starting at octave -1. it's a consequence of the convention that note number 60 is C4. some otheres my use C5 or C3 in which case the 1st octave would be -2 or 0 respectively. i'm not sure what the most common is. i think i have taken my conventions from the appendix of the csound book. it also implies that #69 = A4 which is what i use in my pitch2freq/freq2pitch functions, so i think, for consistency, it would not be a good a idea to change conventions right now. ...may need some more research, but some quick googling revealed that several conventions may be in use

**Comment by RobinSchmidt** [comment]
huh? what it this with the last 3 lines only go up to G?

  StringArray NoteNames
  {
    "C-1","C#-1","D-1","D#-1","E-1","F-1","F#-1","G-1","G#-1","A-1","A#-1","B-1",
    "C0","C#0","D0","D#0","E0","F0","F#0","G0","G#0","A0","A#0","B0",
    "C1","C#1","D1","D#1","E1","F1","F#1","G1","G#1","A1","A#1","B1",
    "C2","C#2","D2","D#2","E2","F2","F#2","G2","G#2","A2","A#2","B2",
    "C3","C#3","D3","D#3","E3","F3","F#3","G3","G#3","A3","A#3","B3",
    "C4","C#4","D4","D#4","E4","F4","F#4","G4","G#4","A4","A#4","B4",
    "C5","C#5","D5","D#5","E5","F5","F#5","G5","G#5","A5","A#5","B5",
    "C6","C#6","D6","D#6","E6","F6","F#6","G6","G#6","A6","A#6","B6",
    "C7","C#7","D7","D#7","E7","F7","F#7","G7","G#7","A7","A#7","B7",
    "C8","C#8","D8","D#8","E8","F8","F#8","G8","G#8","A8","A#8","B8",
    "C9","C#9","D9","D#9","E9","F9","F#9","G9",
    "C10","C#10","D10","D#10","E10","F10","F#10","G10",
    "C11","C#11","D11","D#11","E11","F11","F#11","G11",
  };

**Comment by RobinSchmidt** [comment]
actually, that function is supefluous anyway. juce has it already:

```
String MidiMessage::getMidiNoteName (int note, bool useSharps, bool includeOctaveNumber, int octaveNumForMiddleC)
{
    static const char* const sharpNoteNames[] = { "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B" };
    static const char* const flatNoteNames[]  = { "C", "Db", "D", "Eb", "E", "F", "Gb", "G", "Ab", "A", "Bb", "B" };

    if (isPositiveAndBelow (note, (int) 128))
    {
        String s (useSharps ? sharpNoteNames [note % 12]
                            : flatNoteNames  [note % 12]);

        if (includeOctaveNumber)
            s << (note / 12 + (octaveNumForMiddleC - 5));

        return s;
    }

    return String();
}
```

i'm not sure, but maybe i wrote it before there was a function for that in juce. hmm..don't know

**Comment by RobinSchmidt** [comment]
that function even allows to switch conventions and use flats instead of sharps. nice

**Comment by elanhickler** [comment]
I have a function that is even more robust than that :D but probably overkill

**Pull request merged**
